version: "3.9"

services:

  backend:
    build: ./backend
    container_name: tradesk-backend
    ports:
      - "4000:4000"
    environment:
      PORT: 4000
      JWT_SECRET: "tradesk_super_secret_change_me_2026"
    volumes:
      - db_data:/app
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: tradesk-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  db_data:
